bin: add behavior checks to 'xscreen' xrandr helper

diff --git a/bin/xscreen b/bin/xscreen
--- a/bin/xscreen
+++ b/bin/xscreen
@@ -1,26 +1,52 @@
 #!/bin/bash
 set -euo pipefail
 
-command -v xrandr >/dev/null 2 >&1 || { echo >&2 "Could not find xrandr executable. Aborting." && exit 1; }
+function ensure_xrandr() {
+    command -v xrandr >/dev/null 2>&1 || {
+        echo >&2 "Could not find xrandr executable. Aborting."
+        exit 1
+    }
+}
 
-declare -r primary=$(echo $1 | tr '[:lower:]' '[:upper:]'])
-declare -r active=$(echo ${@:2} | tr '[:lower:]' '[:upper:]')
+function ensure_connected() {
+    local -r displays=$(xrandr | grep " connected" | cut -d' ' -f1)
 
-declare -r displays=$(xrandr | grep " connected" | cut -d' ' -f1)
+    for display in $@; do
+        [[ "${displays[@]}" =~ "$display" ]] || {
+            echo >&2 "$display disconnected. Aborting."
+            exit 1
+        }
+    done
+}
 
-declare xrandr_args=""
-declare last_enabled=$primary
+function xrandr_arguments() {
+    local -r primary=$1
+    local -r secondary=${@:2}
 
-for display in $displays; do
-    if [[ "$primary" == "$display" ]]; then
-        xrandr_args+="--output $display --auto --primary "
-        last_enabled=$display
-    elif [[ "${active[@]}" =~ "$display" ]]; then
-        xrandr_args+="--output $display --auto --right-of $last_enabled "
-        last_enabled=$display
-    else
-        xrandr_args+="--output $display --off "
-    fi
-done
+    local xrandr_args=""
+    local last_enabled=$primary
 
-xrandr $xrandr_args
+    for display in $(xrandr | grep " connected" | cut -d' ' -f1); do
+        if [[ "$primary" == "$display" ]]; then
+            xrandr_args+="--output $display --auto --primary "
+        elif [[ "${secondary[@]}" =~ "$display" ]]; then
+            xrandr_args+="--output $display --auto --right-of $last_enabled "
+            last_enabled=$display
+        else
+            xrandr_args+="--output $display --off "
+        fi
+    done
+
+    echo -n $xrandr_args
+}
+
+function main() {
+    local -r to_enable=$(echo $@ | tr '[:lower:]' '[:upper:]')
+
+    ensure_xrandr
+    ensure_connected $to_enable
+
+    xrandr $(xrandr_arguments $to_enable)
+}
+
+main $@
